### ISSUE TITLE
cfg.json文件如何生成

### ISSUE THREAD

**Issue by xjtuwh** [chkap/crt#1]
你好，请问OTB测试数据中的gt文件cfg.json是如何生成的？

**Comment by xjtuwh** [comment]
还有一个问题，我在pycharm环境下可以正常运行该代码，但是在MATLAB中加载时提示ImportError: No module named tensorflow，请问如何解决该问题？

**Comment by xjtuwh** [comment]
在虚拟环境下可以正常运行，在MATLAB的vot套件下运行不了，提示tensorflow导入失败，请问这是什么原因，我该怎么做呢？

**Comment by chkap** [comment]
手动用python 编写 从 matlab的 cfg 转化过来的

而且 github上有一个 python 的otb上面可以自己获取python的 ccfg

________________________________
发件人: 吴晗 <notifications@github.com>
发送时间: Monday, November 19, 2018 10:51:44 AM
收件人: chkap/crt
抄送: Subscribed
主题: [chkap/crt] cfg.json文件如何生成 (#1)


你好，请问OTB测试数据中的gt文件cfg.json是如何生成的？

―

**Comment by xjtuwh** [comment]
好的，非常感谢您的回复。那第二个问题，我按照您代码中的那样把crt代码放到vot套件中运行，为什么会提示找不到tensorflow呢，而且使用的解析器，python的版本也不对，在MATLAB中设置的是python3（和虚拟环境中使用的一致），但是matlab加载的就是usr/bin/python（不是python3）,请问这该怎么办呢？需要修改环境变量什么的操作吗？

**Comment by chkap** [comment]
记得是要在某一个地方设置 解释器， 忘了， 你再找找看把


________________________________
发件人: 吴晗 <notifications@github.com>
发送时间: Monday, November 19, 2018 9:45:26 PM
收件人: chkap/crt
抄送: kai chen; Comment
主题: Re: [chkap/crt] cfg.json文件如何生成 (#1)


好的，非常感谢您的回复。那第二个问题，我按照您代码中的那样把crt代码放到vot套件中运行，为什么会提示找不到tensorflow呢，而且使用的解析器，python的版本也不对，在MATLAB中设置的是python3（和虚拟环境中使用的一致），但是matlab加载的就是usr/bin/python（不是python3）,请问这该怎么办呢？需要修改环境变量什么的操作吗？

―

**Comment by xjtuwh** [comment]
刚刚拜读了发表在TIP上的文章，真的很棒，但同时有一些想法想要和您探讨一下：
1）您在跟踪的时候回归只使用了一个通道，增多通道数或加深层数对跟踪效果有影响吗？
2）采样使用的是滑动窗搜索，这很耗时？
3）SNR是衡量跟踪置信度的吗？
4）特征提取和跟踪是分开做的对吗，不是端到端训练的，为什么没有对比ResNet的效果呢，使用的VGG的权重是怎么得到的呢？
5）使用PCA降维是为什么呢，出了减少了计算量，有没有使得跟踪精度下降呢？
期待您的回复，多谢！

**Comment by chkap** [comment]
1）  一个通道？ 最终预测是一个map 肯定是一个通道

2）  是的，不耗时，通过卷积实现的

3）  是

4）  分开，你可以尝试端到端，不错的想法，没必要对比resnet，那不是论文重点

5）  减少计算量，你可以试试

________________________________
发件人: 吴晗 <notifications@github.com>
发送时间: Monday, November 19, 2018 9:51:23 PM
收件人: chkap/crt
抄送: kai chen; Comment
主题: Re: [chkap/crt] cfg.json文件如何生成 (#1)


刚刚拜读了发表在TIP上的文章，真的很棒，但同时有一些想法想要和您探讨一下：
1）您在跟踪的时候回归只使用了一个通道，增多通道数或加深层数对跟踪效果有影响吗？
2）采样使用的是滑动窗搜索，这很耗时？
3）SNR是衡量跟踪置信度的吗？
4）特征提取和跟踪是分开做的对吗，不是端到端训练的，为什么没有对比ResNet的效果呢，使用的VGG的权重是怎么得到的呢？
5）使用PCA降维是为什么呢，出了减少了计算量，有没有使得跟踪精度下降呢？
期待您的回复，多谢！

―

**Comment by xjtuwh** [comment]
你好，是在这个设置解析器吗？我在这里改成我的虚拟环境了，但是依然提示导入tensorflow失败，还需要改别的吗？多谢~
![360 20181119215316549](https://user-images.githubusercontent.com/22558591/48711217-9ca8b200-ec45-11e8-8464-d875f221b0b9.jpg)

**Comment by chkap** [comment]
你自己摸索吧，我没那么多时间，

要学会自己解决问题，不是所有问题都会有人给你细心解答的

________________________________
发件人: 吴晗 <notifications@github.com>
发送时间: Monday, November 19, 2018 9:54:49 PM
收件人: chkap/crt
抄送: kai chen; Comment
主题: Re: [chkap/crt] cfg.json文件如何生成 (#1)


你好，是在这个设置解析器吗？我在这里改成我的虚拟环境了，但是依然提示导入tensorflow失败，还需要改别的吗？多谢~
[360 20181119215316549]<https://user-images.githubusercontent.com/22558591/48711217-9ca8b200-ec45-11e8-8464-d875f221b0b9.jpg>

―

**Comment by xjtuwh** [comment]
OK，再次感谢~
